language: go

os:
  - linux
  - osx
  - windows

go:
  - 1.14.x
  - 1.13.x
  - 1.12.x
  - 1.11.x
  - tip

before_install:
  - go get -u -v golang.org/x/tools/cmd/cover
  - go get -u -v github.com/modocache/gover
  - go get -u -v github.com/mattn/goveralls
  - go get -t -v ./...

script:
  - go test -v -cover -race ./... -coverprofile=.coverprofile

  # send coverage
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=.coverprofile -service=travis-ci

jobs:
  allow_failures:
    - go: tip

  include:
    - stage: cross compilation
      script:
        - GOOS=linux go build
        - GOOS=darwin go build
        - GOOS=freebsd go build
        - GOOS=windows go build
        - GOARCH=386 go build
