sudo: false
language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

before_install:
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls
  # - go get -v github.com/golang/lint/golint

install:
  - go get -d -t -v ./...
  - go install -v

script:
  - go vet ./...
  # - $HOME/gopath/bin/golint ./...
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci

-after_success:
  - coveralls
